development:
  adapter: postgresql
  database: events_development
  host: localhost
  port: 5432
  pool: 5

test:
  adapter: postgresql
  database: events_test
  host: localhost
  port: 5432
  pool: 5

production:
  adapter: postgresql
  database: events_production
  host: localhost
  port: 5432
  pool: 5
